apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: web-app
type: Opaque
data:
  root-password: MTIzNDU2  # 123456 en base64
  database-name: bWlfZGI=   # mi_db en base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: web-app
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mi_db;
    USE mi_db;

